Update azure-functions-app-python.yml

diff --git a/.github/workflows/azure-functions-app-python.yml b/.github/workflows/azure-functions-app-python.yml
--- a/.github/workflows/azure-functions-app-python.yml
+++ b/.github/workflows/azure-functions-app-python.yml
@@ -206,3 +206,29 @@ jobs:
 
       # Package and deploy ResumeUploadUI to resumefinalclass Function App
       - name: Package ResumeUploadUI Function App
+        run: |
+          RESUME_DIR=$(find . -type d -name "*[Rr][Ee][Ss][Uu][Mm][Ee][Uu][Pp][Ll][Oo][Aa][Dd][Uu][Ii]*" -print -quit)
+          if [ -n "$RESUME_DIR" ]; then
+            echo "Packaging ResumeUploadUI from $RESUME_DIR"
+            mkdir -p temp/ResumeUploadUI
+            cp -r "$RESUME_DIR"/* temp/ResumeUploadUI/
+            cd temp
+            zip -r ResumeUploadUI.zip ResumeUploadUI
+            mv ResumeUploadUI.zip "$GITHUB_WORKSPACE"
+            echo "Listing contents of ResumeUploadUI.zip:"
+            unzip -l "$GITHUB_WORKSPACE/ResumeUploadUI.zip"
+          else
+            echo "ResumeUploadUI directory not found, failing..."
+            exit 1
+          fi
+
+      - name: Deploy ResumeUploadUI to resumefinalclass Function App
+        uses: Azure/functions-action@v1
+        with:
+          app-name: ${{ env.resumefinalclass }}
+          package: 'ResumeUploadUI.zip'
+
+      # Restart resumefinalclass Function App
+      - name: Restart resumefinalclass Function App
+        run: |
+          az functionapp restart --name ${{ env.resumefinalclass }} --resource-group groupproject
